config/routes.rb
Rails.application.routes.draw do
  resources :books, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    def self.to_csv(options = {})
        CSV.generate(options) do |csv|
            csv << column_names
            all.each do |book|
                csv << book.attributes.values_at(*column_names)
            end
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all

    respond_to do |format|
      format.html
      format.csv { send_data @books.to_csv }
      format.xls { send_data @books.to_csv(col_sep: "\t")}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<h1>Listado de libro</h1>
<hr />
<p>
    
    <%= link_to "CSV", books_path(format: "csv") %>
    <%= link_to "Excel", books_path(format: "xls") %>
</p>
<table>
    <tr>
        <th>titulo</th>
        <th>autor</th>
        <th>editorial</th>
        <th>genero</th>
    </tr>
    <% @books.each do |book|%>
        <tr>
            <td><%= book.title %></td>
            <td><%= book.author %></td>
            <td><%= book.publisher %></td>
            <td><%= book.genre %></td>
        </tr>
    <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DjExportCsv</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>